import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-black text-white max-w-screen-md mx-auto py-10 px-5">
        {children}
      </body>
    </html>
  )
}
