import type { Metadata } from "next";
import "../globals.css";
import Navigation from "@/components/navigation";
import HeaderNavigation from "@/components/header-navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="mb-20">
      <HeaderNavigation />
      <Navigation />
      {children}
    </div>
  );
}
